<!-- STANDARD MICROSOFT FOOTER FOR QUERY PAGES -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ks_c_5601-1987">
<hr width=500 align=left>
<p>
<table border="0" cellpadding="0" cellspacing="0" width="500">
	<tr>
		<!-- IIS GIF -->
	    <td>
				<a href="http://www.microsoft.com/iis"><img src="nts_iis.GIF" alt="Internet Information Server를 배우십시오!" width="88" height="31" border="0"></a>
			</td>

		<!-- Microsoft Legal Info -->
        <td align=center>
			<font style="font:arial; font-size: 8pt">&copy; 1998 Microsoft Corporation. All rights reserved.<br></font><a href="http://www.microsoft.com/korea/misc/cpyright.htm"><font style="font:arial; font-size: 9pt">사용권에 대한 고지 사항</font></a>
       </td>

		<!-- Best with IE GIF -->
       <td align=right>
			<a href="http://www.microsoft.com/ie_intl/ko"><img src="IE.GIF" alt="Internet Explorer를 다운로드하십시오!" width="88" height="31" border="0"></a>
        </td>
    </tr>
</table>
